#define ERROR      -1
#define END        0
#define AUTO       1
#define BREAK      2
#define CASE       3
#define CHAR       4
#define CONST      5
#define CONTINUE   6
#define DEFAULT    7
#define DO         8
#define DOUBLE     9
#define ELSE       10
#define ENUM       11
#define EXTERN     12
#define FLOAT      13
#define FOR        14
#define GOTO       15
#define IF         16
#define INLINE     17
#define INT        18
#define LONG       19
#define REGISTER   20
#define RESTRICT   21
#define RETURN     22
#define SHORT      23
#define SIGNED     24
#define SIZEOF     25
#define STATIC     26
#define STRUCT     27
#define SWITCH     28
#define TYPEDEF    29
#define UNION      30
#define UNSIGNED   31
#define VOID       32
#define VOLATILE   33
#define WHILE      34
#define CONSTANT   35
#define STRING_LITERAL 36
#define ELLIPSIS   37
#define RIGHT_ASSIGN 38
#define LEFT_ASSIGN 39
#define ADD_ASSIGN 40
#define SUB_ASSIGN 41
#define MUL_ASSIGN 42
#define DIV_ASSIGN 43
#define MOD_ASSIGN 44
#define AND_ASSIGN 45
#define XOR_ASSIGN 46
#define OR_ASSIGN  47
#define RIGHT_OP   48
#define LEFT_OP    49
#define INC_OP     50
#define DEC_OP     51
#define PTR_OP     52
#define AND_OP     53
#define OR_OP      54
#define LE_OP      55
#define GE_OP      56
#define EQ_OP      57
#define NE_OP      58
#define VARIANT    59
#define COMMENT    60
#define PASS       61
